name: ib_async

on: [ push, pull_request ]

jobs:
  build:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "pypy3.10", "pypy3.11" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install mypy types-dataclasses .

      - name: MyPy static code analysis
        run: |
          mypy -p ib_async
